Description: >
    NomanIkram-CfnAssignment-Nested-Stack-BastionHost-Configuration

Parameters:
  ProjectName:
    Description: An environment name that will be prefixed to resource names
    Type: String
    Default: "NomanIkram-Cfn-Assignment"

  Environnment:
    Description: An environment name that will be prefixed to resource names
    Type: String
    Default: "Dev"


  InstanceAMI:
    Description: AMI used for the Setting up MySql
    Type: String
    Default: "ami-0ee02acd56a52998e"

  EC2InstanceType:
    Description: InstanceType used for the Setting up MySql
    Type: String
    Default: "t2.micro"

  SSHKey:
    Description: Secret Key Name
    Type: String
    Default: "nomanikram-secretkey"

  PublicSubnet1a:
    Description: PublicSubnet1a
    Type: String
    Default: "default"

  BastionHostSG:
    Description: BastionHostSG
    Type: String
    Default: "default"

Resources:
  BastionHost:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref InstanceAMI
      InstanceType: !Ref EC2InstanceType
      KeyName: !Ref SSHKey
      SubnetId: !Ref PublicSubnet1a
        # Fn::ImportValue:
        #   PublicSubnet1a
      SecurityGroupIds:
        - Ref: BastionHostSG
        # - Fn::ImportValue:
        #     BastionHostSG
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environnment}-EC2-BastionHost'


Outputs:
  BastionHostPublicIp:
    Description: Security Group For Database
    Value:
      Fn::GetAtt:
       - BastionHost
       - PublicIp
    Export:
      Name: BastionHostPublicIp
