Description: >
    NomanIkram-CfnAssignment-Nested-Stack-ASG-Configuration

Parameters:
  ProjectName:
    Description: An environment name that will be prefixed to resource names
    Type: String
    Default: "NomanIkram-Cfn-Assignment"

  Environnment:
    Description: An environment name that will be prefixed to resource names
    Type: String
    Default: "Dev"

Resources:
  FlaskAppASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: 'FlaskAppASG'
      MinSize: "2"
      MaxSize: "4"
      DesiredCapacity: "2"
      HealthCheckGracePeriod: 300
      TargetGroupARNs:
        #- Ref : FlaskAppTargetGroup
        - Fn::ImportValue:
            FlaskAppTargetGroup
      LaunchTemplate:
        LaunchTemplateId: #!Ref FlaskAppLaunchTemplate
          Fn::ImportValue:
              FlaskAppLaunchTemplate
        Version: #!GetAtt DatabaseStack.Outputs.FlaskAppLaunchTemplate.LatestVersionNumber
          Fn::ImportValue:
            LaunchTemplateVersion

      VPCZoneIdentifier:
        #- !Ref PrivateSubnet1b
        #- !Ref PrivateSubnet2b
        - Fn::ImportValue:
            PrivateSubnet1b
        - Fn::ImportValue:
            PrivateSubnet2b
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environnment}-ASG-FlaskApp'
          PropagateAtLaunch: "true"
