Description: >
    NomanIkram-CfnAssignment-Nested-Stack-ALB-Configuration

Parameters:
  ProjectName:
      Description: An environment name that will be prefixed to resource names
      Type: String
      Default: "NomanIkram-Cfn-Assignment"

  Environnment:
    Description: An environment name that will be prefixed to resource names
    Type: String
    Default: "Dev"


Resources:

  FlaskAppTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 8
      HealthyThresholdCount: 2
      Port:  80
      Protocol: HTTP
      UnhealthyThresholdCount: 5
      VpcId: #!Ref VPC
        Fn::ImportValue:
          VPC

  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: 'internet-facing'
      SecurityGroups:
        #- Ref: LoadBalancerSG
       - Fn::ImportValue:
          LoadBalancerSG
      Subnets:
        #- Ref: PublicSubnet1a
        #- Ref: PublicSubnet2a
        - Fn::ImportValue:
            PublicSubnet1a
        - Fn::ImportValue:
            PublicSubnet2a

      Type: application
      Tags:
        - Key: Name
          Value: !Sub 'NomanIkram-FlaskApp-ALB'

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
      - Type: forward
        TargetGroupArn:
          Ref: FlaskAppTargetGroup
      LoadBalancerArn: !Ref ALB
      Port: '80'
      Protocol: HTTP

Outputs:
  FlaskAppTargetGroup:
    Description: The subnet ID to use for public web servers
    Value: !Ref FlaskAppTargetGroup
    Export:
      Name: FlaskAppTargetGroup

  AlbDnaAddress:
    Description: The DNSName of the load balancer
    Value: !Sub 'http://${ALB.DNSName}' # !Join [ "", [ "http://", !GetAtt ALB.DNSName ]]
    Export:
      Name: !Sub '${ProjectName}-${Environnment}-LB-DNS-Link'
